'use strict';
const API_KEY=(typeof CONFIG !== 'undefined' && CONFIG.API_KEY) ? CONFIG.API_KEY : '';
const API_URL=`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-lite:generateContent?key=${API_KEY}`;
const $=id=>document.getElementById(id);
const themeToggle=$('themeToggle');
const generateBtn=$('generateBtn');
const copyBtn=$('copyBtn');
const status=$('statusMessage');
const loading=$('loadingOverlay');
const sender=$('senderName');
const recipient=$('recipientName');
const recipientTitle=$('recipientTitle');
const recipientAddress=$('recipientAddress');
const schoolName=$('schoolName');
const studentId=$('studentId');
const tone=$('tone');
const dateInput=$('letterDate');
const contextText=$('context');
const paper={sender:$('paperSender'),id:$('paperSenderId'),org:$('paperSenderOrg'),date:$('paperDate'),recipient:$('paperRecipient'),recipientTitle:$('paperRecipientTitle'),recipientAddress:$('paperRecipientAddress'),subject:$('paperSubjectLine'),salutation:$('paperSalutation'),body:$('paperBody'),closing:$('paperClosing'),signature:$('paperSignature')};
const closings={formal:'Yours sincerely,',casual:'Cheers,',warm:'With love and warmth,',confident:'With confidence,',sincere:'With sincere regards,'};
const toneLabels={formal:'Formal and professional',casual:'Casual and friendly',warm:'Warm and affectionate',confident:'Confident and assertive',sincere:'Sincere and heartfelt'};
const saved=localStorage.getItem('letterStudio_theme');
document.documentElement.dataset.theme=saved==='light'?'light':'dark';
themeToggle.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem('letterStudio_theme',next);});
const formatDate=val=>{const d=new Date(val?`${val}T00:00:00`:'');return isNaN(d)?new Date().toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'}):d.toLocaleDateString('en-US',{year:'numeric',month:'long',day:'numeric'});};
const updatePreview=()=>{const name=sender.value.trim()||'Your Name';paper.sender.textContent=name;paper.signature.textContent=name;paper.org.textContent=schoolName.value.trim();paper.id.textContent=studentId.value.trim()?`ID: ${studentId.value.trim()}`:'';const recipientName=recipient.value.trim()||'Recipient Name';paper.recipient.textContent=recipientName;paper.recipientTitle.textContent=recipientTitle.value.trim();paper.recipientAddress.textContent=recipientAddress.value.trim();const toneValue=tone.value;paper.salutation.textContent=toneValue==='formal'?`Respected ${recipientTitle.value.trim()||recipientName},`:toneValue==='casual'||toneValue==='warm'?`Hi ${recipientName.split(' ')[0]},`:`Dear ${recipientTitle.value.trim()||recipientName},`;paper.date.textContent=formatDate(dateInput.value);paper.closing.textContent=closings[toneValue]||'Sincerely,';};
['input','change'].forEach(evt=>[sender,recipient,recipientTitle,recipientAddress,schoolName,studentId,tone,dateInput].forEach(el=>el.addEventListener(evt,updatePreview)));
updatePreview();
const showStatus=(text='',type='')=>{status.textContent=text;status.className='status-message'+(type?` is-${type}`:'');};
const setLoading=on=>{generateBtn.disabled=on;loading.classList.toggle('is-visible',on);generateBtn.querySelector('.btn-generate__text').textContent=on?'Generating…':'Generate Letter';};
const textToHtml=text=>text.trim().split(/\r?\n\s*\r?\n/).map(p=>`<p>${p.replace(/\r?\n/g,'<br>')}</p>`).join('');
const buildPlainTextLetter=()=>{const blocks=[paper.sender.textContent,paper.date.textContent,'',paper.recipient.textContent,paper.recipientAddress.textContent,'',paper.subject.textContent?`Subject: ${paper.subject.textContent}`:'',paper.salutation.textContent,'',paper.body.innerText,'',paper.closing.textContent,paper.signature.textContent];return blocks.filter((v,i)=>v||i<3).join('\n').replace(/\n{3,}/g,'\n\n');};
const callGemini=async()=>{const prompt=`You are a letter writer. Use tone ${toneLabels[tone.value]||tone.value}. From ${sender.value.trim()||'Sender'}${schoolName.value.trim()?' ('+schoolName.value.trim()+')':''}${studentId.value.trim()?' [ID: '+studentId.value.trim()+']':''}. To ${recipientTitle.value.trim()||''} ${recipient.value.trim()||'Recipient'}. Address ${recipientAddress.value.trim()}. Context: ${contextText.value.trim()}. Write the letter body only.`.trim();const res=await fetch(API_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:0.8,maxOutputTokens:1024}})});if(!res.ok){const data=await res.json().catch(()=>null);throw new Error(data?.error?.message||`HTTP ${res.status}`);}const data=await res.json();const text=data?.candidates?.[0]?.content?.[0]?.text||data?.candidates?.[0]?.content?.parts?.[0]?.text||data?.candidates?.[0]?.content?.[0]?.parts?.[0]?.text||'';let subject='';if(tone.value==='formal'){const m=text.match(/SUBJECT:\s*(.+?)(?:\r?\n|$)/);if(m){subject=m[1].trim();text=text.replace(/SUBJECT:\s*.+?\r?\n+/,'').trim();}}return{text,subject};};
generateBtn.addEventListener('click',async()=>{if(!sender.value.trim()){showStatus('Enter your name','error');sender.focus();return;}if(!recipient.value.trim()){showStatus('Enter recipient name','error');recipient.focus();return;}if(!contextText.value.trim()){showStatus('Enter letter purpose','error');contextText.focus();return;}if(!API_KEY){const message='Configuration Required: Please add your API key to config.js for local use.';console.warn(message);showStatus(message,'error');return;}showStatus('');setLoading(true);try{const {text,subject}=await callGemini();paper.body.classList.remove('is-animated');paper.body.innerHTML=textToHtml(text);void paper.body.offsetWidth;paper.body.classList.add('is-animated');paper.subject.textContent=subject;showStatus('Letter generated','success');setTimeout(()=>showStatus(''),3000);}catch(e){console.error(e);showStatus(`Error: ${e.message}`,'error');}finally{setLoading(false);}});copyBtn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(buildPlainTextLetter());const html=copyBtn.innerHTML;copyBtn.textContent='✓ Copied!';copyBtn.style.color='var(--success-color)';copyBtn.style.borderColor='var(--success-color)';setTimeout(()=>{copyBtn.innerHTML=html;copyBtn.style.color='';copyBtn.style.borderColor='';},2000);}catch(e){console.error(e);showStatus('Could not copy','error');}});
